packages:
  - '*/src'
catalog:
  '@eslint/js': ^9.39.2
  '@slidev/cli': ^52.11.0
  '@slidev/client': ^52.6.0
  '@slidev/theme-default': latest
  '@slidev/theme-seriph': latest
  '@types/node': ^22.11.0
  '@types/prompts': ^2.4.9
  '@commitlint/types': ^20.2.0
  '@commitlint/config-conventional': ^20.2.0
  globals: ^16.5.0
  commitlint: ^20.2.0
  conventional-changelog-atom: ^5.0.0
  husky: ^9.1.7
  jiti: ^2.6.1
  lint-staged: ^16.2.7
  eslint: ^9.39.2
  tsx: ^4.20.6
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  execa: ^9.6.0
  prettier: ^3.7.4
  typescript: ^5.9.3
  typescript-eslint: ^8.50.0
  rimraf: ^6.1.2
  unocss: ^66.5.10
  prompts: ^2.4.2
  vite: ^7.3.0
onlyBuiltDependencies:
  - esbuild
  - playwright-chromium
  - unrs-resolver
